export const APP_SHOW_LOADER = "APP_SHOW_LOADER";
export const APP_HIDE_LOADER = "APP_HIDE_LOADER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_AUTH_SUCCESS = "AUTH_AUTH_SUCCESS";
export const AUTH_AUTO_LOGIN_SUCCESS = "AUTH_AUTO_LOGIN_SUCCESS";
export const AUTH_SIGN_OUT_SUCCESS = "AUTH_SIGN_OUT_SUCCESS";

/*WORKSPACE*/
export const AUTH_CREATE_WORKSPACE = "AUTH_CREATE_WORKSPACE";
export const AUTH_ADD_WORKSPACE_TO_STATE = "AUTH_ADD_WORKSPACE_TO_STATE";
export const AUTH_UPDATE_WORKSPACE = "AUTH_UPDATE_WORKSPACE";
export const AUTH_UPDATE_STATE_WORKSPACE = "AUTH_UPDATE_STATE_WORKSPACE";
export const AUTH_DELETE_WORKSPACE = "AUTH_DELETE_WORKSPACE";
export const AUTH_GET_WORKSPACES = "AUTH_GET_WORKSPACES";
export const AUTH_GET_LIMITED_WORKSPACES_STATE =
  "AUTH_GET_LIMITED_WORKSPACES_STATE";
export const GET_WORKSPACE = "GET_WORKSPACE";
export const GET_LATEST_WORKSPACES = "GET_LATEST_WORKSPACES";
export const AUTH_DELETE_WORKSPACE_FROM_STATE =
  "AUTH_DELETE_WORKSPACE_FROM_STATE";


